/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/NTHU-LSALAB/KubeShare/pkg/apis/kubeshare/v1"
	scheme "github.com/NTHU-LSALAB/KubeShare/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SharePodsGetter has a method to return a SharePodInterface.
// A group's client should implement this interface.
type SharePodsGetter interface {
	SharePods(namespace string) SharePodInterface
}

// SharePodInterface has methods to work with SharePod resources.
type SharePodInterface interface {
	Create(*v1.SharePod) (*v1.SharePod, error)
	Update(*v1.SharePod) (*v1.SharePod, error)
	UpdateStatus(*v1.SharePod) (*v1.SharePod, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.SharePod, error)
	List(opts metav1.ListOptions) (*v1.SharePodList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SharePod, err error)
	SharePodExpansion
}

// sharePods implements SharePodInterface
type sharePods struct {
	client rest.Interface
	ns     string
}

// newSharePods returns a SharePods
func newSharePods(c *KubeshareV1Client, namespace string) *sharePods {
	return &sharePods{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sharePod, and returns the corresponding sharePod object, and an error if there is any.
func (c *sharePods) Get(name string, options metav1.GetOptions) (result *v1.SharePod, err error) {
	result = &v1.SharePod{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sharepods").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SharePods that match those selectors.
func (c *sharePods) List(opts metav1.ListOptions) (result *v1.SharePodList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SharePodList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sharepods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sharePods.
func (c *sharePods) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sharepods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a sharePod and creates it.  Returns the server's representation of the sharePod, and an error, if there is any.
func (c *sharePods) Create(sharePod *v1.SharePod) (result *v1.SharePod, err error) {
	result = &v1.SharePod{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sharepods").
		Body(sharePod).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sharePod and updates it. Returns the server's representation of the sharePod, and an error, if there is any.
func (c *sharePods) Update(sharePod *v1.SharePod) (result *v1.SharePod, err error) {
	result = &v1.SharePod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sharepods").
		Name(sharePod.Name).
		Body(sharePod).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *sharePods) UpdateStatus(sharePod *v1.SharePod) (result *v1.SharePod, err error) {
	result = &v1.SharePod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sharepods").
		Name(sharePod.Name).
		SubResource("status").
		Body(sharePod).
		Do().
		Into(result)
	return
}

// Delete takes name of the sharePod and deletes it. Returns an error if one occurs.
func (c *sharePods) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sharepods").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sharePods) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sharepods").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sharePod.
func (c *sharePods) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SharePod, err error) {
	result = &v1.SharePod{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sharepods").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
