apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: pod2
  annotations:
    "kubeshare/gpu_request": "0.6"
    "kubeshare/gpu_limit": "1.0"
    "kubeshare/gpu_mem": "3145728000"
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: tf
    image: tensorflow/tensorflow:1.15.2-gpu-py3
    command: ["sh", "-c", "curl -s https://lsalab.cs.nthu.edu.tw/~ericyeh/KubeShare/demo/mnist.py | python3 -"]
  restartPolicy: OnFailure
